FROM idealo/nima-gpu 

COPY src /src
COPY entrypoints /src/entrypoints

WORKDIR /src

RUN pip install -r requirements.txt
RUN pip install awscli --upgrade --user

ENV PYTHONPATH='/src/:$PYTHONPATH'

ENTRYPOINT ["entrypoints/entrypoint.train.gpu.sh"]
